### ISSUE TITLE
Fingerprinting on mobile devices (Xamarin)

### ISSUE THREAD

**Issue by Nekromancer** [AddictedCS/soundfingerprinting#114]
@AddictedCS Do you have any experience with using SoundFingerprinting on Xamarin? The case i'm looking at is to fingerprint audio on device, transfer HashedFingerprints to backend service where the recognitions will occur.

As far as i know i could use `SoundFingerprintingAudioService` with wav files or `BassAudioService` (they claim to support Xamarin). 

Is fingerprinting on device and querying on server possible before https://github.com/AddictedCS/soundfingerprinting/issues/108 ?

**Comment by AddictedCS** [comment]
@Nekromancer, yes you can use `SoundFingerprintingAudioService` passing raw audio data to it. There has to be a way to get it using `Xamarin` framework for this as wave format is just an uncompressed array of audio samples.

Querying directly with `HashedFingerprints` is possible since `v6.1.0-beta1`. It will get into the next stable release as well.
