### ISSUE TITLE
how to match two audio files having common content but they starts at different timings in both audio files

### ISSUE THREAD

**Issue by kharsh90** [AddictedCS/soundfingerprinting#159]
The Scenario is as given below
I have two audio files A and B. both audio files have some content "XYZ".
This XYZ audio starts at second 1 in Audio A and starts at second 15 in Audio B.
I have generated audio fingerprints of Audio A and trying to match Audio B with them.

Expected result: since content XYZ is there in Audio B as well from 15th second onwards, I am expecting Audio B will get match with Audio A's fingerprints.
Actual Result: when I try to match Audio B with audio fingerprints in the DB / memory, it does not give a match and returns Tracknfo as null.

Can you please help me out in this issue and also let me know the significance of StartsAt and SecondsToAnalyze properties. Can I add some custom configurations which can help me to get match in this scenario

**Comment by AddictedCS** [comment]
The audio from A should match the B file. Do not specify any `StartsAt` and `SecondsToAnalyze` parameters.
The results should provide you with the relative timeframe where the match occurred.

**Comment by svaza** [comment]
Hi Sergiu,

Another question with same scenario.
Audio A length of 43seconds, hashed and fingerprints loaded in memory

Audio B to be matched, length of 10 seconds. The contents of Audio B starts at 20s in Audio A.
The expected is that since AudioB is present in Audio A in later part of audio, it should match. 
but after specifying startsAt and duration as 0, it still didnt match.

I am using AudioFingerprintingService.
