### ISSUE TITLE
Emy storage problem in docker

### ISSUE THREAD

**Issue by AmirHossein484** [AddictedCS/soundfingerprinting#164]
Hi,
I'm using soundfingerprinting version 7.5.5 in a asp.net core service on windows server 2019, and I'm using emy storage as a database,
Everything works fine until I get to about 950 songs. after that emy storage stop responding! I have restarted docker, windows and checked everything crossed my mind but Emy is not working anymore, When I tried to lunch emy control panel, browser opens but nothing is displayed and the screen remains white.
Is this because I'm using community version of emy or something else? 
The log files in replication folder are about 500 mb in total, Is it normal?

I emailed you twice in the last two weeks to buy the Emy Enterprise version, but unfortunately I did not receive a reply.

Thanks

**Comment by AddictedCS** [comment]
@AmirHossein484 this behavior is not OK. It is a sign of having not enough RAM allocated for the Docker process. How is your docker configured? Does it have enough memory?

**Comment by amirh484fj** [comment]
> @AmirHossein484 this behavior is not OK. It is a sign of having not enough RAM allocated for the Docker process. How is your docker configured? Does it have enough memory?

Thanks for your help, I'm new to Docker, I increased the RAM in settings and the problem was solved until I reached about 17k audio tracks, now docker container stopped automatically after starting even though docker has been set to use 24GB of my computer's RAM.

System.OutOfMemoryException

The question is, How much RAM is needed for an audio track (about 5 min), Is this normal to face OutOfMemoryException after adding about 17k tracks?

Thanks

**Comment by AddictedCS** [comment]
24GB of RAM should be enough to fit 2,400 hours of content. 17K audio tracks is with an average of 5 minutes is 1.400 hours so make sure your Docker host is not consuming RAM dedicated to your Docker container.
