### ISSUE TITLE
[Question] [Not a bug] Is SoundFingerprinting.Emy the same as the repository as SoundFingerprinting?

### ISSUE THREAD

**Issue by jeffward01** [AddictedCS/soundfingerprinting#167]
Hello!

Very cool project! The world needs something like this!

I saw your recent changes to the [ReadMe](https://github.com/AddictedCS/soundfingerprinting/commit/218daa12b500b3ff4af9cb84625033f15d017a71#:~:text=Paired%20with%20%5BSoundFingerprinting.Emy%5D%5Bemy-nuget%5D%20it%20can%20be%20used%20to%20generate%20fingerprints%20from%20video%20content%20as%20well.) in the repository [soundfingerprinting](https://github.com/AddictedCS/soundfingerprinting).

I am unclear on one statement:

You say 

>_soundfingerprinting_ is a C# framework designed for companies, enthusiasts, researchers in the fields of audio and digital signal processing, data mining and audio recognition...... (then below)

>  Paired with [SoundFingerprinting.Emy][emy-nuget] it can be used to generate fingerprints from video content as well. 

**Questions:**
1.) Is the [SoundFingerprinting.Emy](https://www.nuget.org/packages/SoundFingerprinting.Emy) code also included in the repository [SoundFingerprinting](https://github.com/AddictedCS/soundfingerprinting)? Or is it a completly seperate codebase?

2.) Does this mean in order to use the video fingerprinting we need to use (2) SoundFingerprinting libraries ([1] SoundFingerprinting & [2] SoundFingerprinting.Emy) which are in seperate git repositories? Or can we still use only the code from [SoundFingerprinting](https://github.com/AddictedCS/soundfingerprinting) and still achieve video fingerprinting?

Thanks!

**Comment by AddictedCS** [comment]
Hey @jeffward01 
1 - soundfingerprinting.emy is available on Nuget, the source code though is still in private repo. I plan to make it public soon. 
2 - in order to create video fingerprints you need `FFmpegDataService` to be able to read/decode/transform frames to the appropriate format. `FFmpegDataService` is available in SoundFingerprinting.Emy. So you need both SF and SF.Emy for video fingerprinting.

Opening the SF.Emy repo to the public will take some time as parts of the code needs to be merged to SoundFingerprinting to make the interfaces generic for Audio/Video processing.

**Comment by jeffward01** [comment]
Thanks! This answers my question perfectly, I appreciate it!

**Comment by 0x6E703434** [comment]
> Opening the SF.Emy repo to the public will take some time as parts of the code needs to be merged to SoundFingerprinting to make the interfaces generic for Audio/Video processing.

Hello @AddictedCS !

Where can we follow the progress on the code merge?
