### ISSUE TITLE
Emy hits the memory limit

### ISSUE THREAD

**Issue by uoziod** [AddictedCS/soundfingerprinting#205]
On the main page it's said that Emy is using persistent storage for the fingerprints, but as far as I can see it still is loading them in memory on restart. I see that there's a possibility to replace InMemoryModelService with something else, but wouldn't it be nice to have something like DiskModelService embedded in Emy with an option to use it instead of InMemory?

**Comment by AddictedCS** [comment]
From the email reply:

A short answer: Emy never intended to store large amounts of audio content (more than 1,000 hours), as its main goal was to precisely identify the start-end location of the match which is highly sought in other business domains. Building a Shazam style storage requires not only changes in the storage but also in the fingerprint signature, which is not in scope of this project.

A longer answer: Emy uses locality sensitive hashing to cross-match audio fingerprints. Any LSH-based algorithm (or more broadly any approximate nearest neighbor algorithm!) uses a RAM based storage, that is an inherent limitation of it (be it [faiss](https://github.com/facebookresearch/faiss), [HNSW](https://github.com/nmslib/hnswlib), or literally any other [ANN](https://ann-benchmarks.com/) algo, with a notable exception of [DiskANN](https://github.com/microsoft/DiskANN), which may or may not be suitable for SoundFingerprinting). Rewriting the storage is nowhere near a trivial task that I'm not interested in pursuing at this point due to reasons described in the short answer. 

You can take a look at Milvus and PaddleSearch and see if their implementation uses less RAM and suits your purposes: https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/audio_searching
AFAIK they face the exact same dilema and their demo states that for CN-Celeb a dataset of mere 1024 hours of content they needed a 132GB RAM machine.
