### ISSUE TITLE
How can we save IModelService modelService into a text file and read back?

### ISSUE THREAD

**Issue by MonsterMMORPG** [AddictedCS/soundfingerprinting#65]
I dont see any option to save

How can we save it into a text file and then later read it back?

It says it supports several databases but i dont see any documentation about it either

I have MSSQL so i can use it too

I found this script and it works on MSSQL : https://github.com/AddictedCS/soundfingerprinting/blob/master/src/Scripts/DBScript.sql

But how about the rest? How do we use SQL as storage?

**Comment by MonsterMMORPG** [comment]
Ok i am removing my duplicates right now with using 

`    private readonly IModelService modelService = new InMemoryModelService(); // store fingerprints in RAM`

but it already uses 7 gb ram after 2400 songs are processed and put into ram

SQL server is a must

**Comment by AddictedCS** [comment]
@MonsterMMORPG Did you read the front page https://github.com/AddictedCS/soundfingerprinting documentation? It clearly lists available storage options.

**Comment by Medisex64** [comment]
There are two more storage options other than RAM, which are SQL Server and Solr. I've personally tried them all, fastest of which has been Solr. I also tried MongoDB but as stated that is not production ready so go for Solr for persistent storage. The only thing which I yet have not figured out how to better optimize are the first time queries which take more time and that possibly is because I know almost nothing about Solr. This project forced me to get it working and I was surprised.
For SQL Server use [this script](https://github.com/AddictedCS/soundfingerprinting.sql/blob/release/3.1.x/src/Scripts/DBScript.sql)  and 3.x series.

**Comment by MonsterMMORPG** [comment]
@Medisex64  ty now it works. although SQL storage is much much slower than ram :(
