### ISSUE TITLE
Sample Rate support for 48000

### ISSUE THREAD

**Issue by Nekromancer** [AddictedCS/soundfingerprinting#86]
Hi,

I have to add wav file to database that have sample rate of 48000. Can you add support for this?

**Comment by AddictedCS** [comment]
You can try `SoundFingerprinting.NAudio` for now. I will add support for 48Khz in `SoundFingerprintingAudioService` in the upcoming releases.

**Comment by Nekromancer** [comment]
Yes, i'm doing that for now, but i'm tring to lean towards .net core :)

**Comment by AddictedCS** [comment]
Support for 48KHz files has been added to version 5.2.0. 

Downsampling from 48KHz to 5512Hz requires a non-integer sampling, thus an intermediate upsampling to 336KHz happens before getting to 5512Hz. In other words, 7/61 ratio is used to downsample the signal.

Please test it and let me know if there are any issues. 

The signal aliases slightly but that's expected since right now SoundFingerprintingAudioService uses simple convolutional low pass filters.

<img width="1241" alt="screen shot 2018-04-29 at 3 37 54 pm" src="https://user-images.githubusercontent.com/1202115/39406691-6ed52340-4bc3-11e8-8177-bd3b289ee05c.png">

**Comment by Nekromancer** [comment]
Thanks, everything seems to be working just fine
