### ISSUE TITLE
Indepth algorithm walkthrough

### ISSUE THREAD

**Issue by jakoss** [AddictedCS/soundfingerprinting#89]
Have you ever considered making an indepth algorithm walkthrough, in form of a small book or something similar? I would love to learn more about music recognition, but code without theoretical context is hard to start with. Or maybe you know about some materials on internet that could get me (or anybody interested) started with the topic?

**Comment by worldveil** [comment]
I wrote a thing here:
https://willdrevo.com/fingerprinting-and-audio-recognition-with-python/

**Comment by Nekromancer** [comment]
@worldveil That's awesome! Well and simply put description. I have a question though - is finding peaks by image processing library standard practice in these types of algorithms? I find it a little bit odd - it seems to me like something that can be analyzed using some clever math (i'm **not** a math expect, since the question)

**Comment by worldveil** [comment]
What clever math did you have in mind?

**Comment by Nekromancer** [comment]
Well, like i wrote, i'm not a math expert :). I asked if this is standard practice because i once had an assignment to port echoprint codegen fingerprinting algorithm to another language (C -> Rust with a lot of optimizations on the way) and there was no image recognition used there. Granted - it was a blind rewrite, i didn't care much about the algorithm itself, but i think i would recognize that :)

**Comment by worldveil** [comment]
These are the type of peak finding algorithms you'll likely want:
http://people.cs.bris.ac.uk/~konrad/courses/2018_2019_COMS10007/slides/20-peak-finding-2d-no-pause.pdf

Though you'd need to adapt them slightly for larger neighborhoods around "peaks". 

I simply used existing versions from `scipy` because they were fast & deterministic.

**Comment by AddictedCS** [comment]
@Nekromancer I've posted algorithm overview here https://emysound.com/blog/open-source/2020/06/12/how-audio-fingerprinting-works.html

Many ideas pilled up over the years, and I finally put them into words.

Thanks @worldveil for the reference. I remember stumbling on your article on HN many years ago. It actually seeded the idea to write my own overview of audio fingerprinting.

Will appreciate any feedback!
