### ISSUE TITLE
How can I do duplicate matching when the QueryFingerprintService is inaccesable due to it's protection level?

### ISSUE THREAD

**Issue by perivar** [AddictedCS/soundfingerprinting#93]
Hi,
I am trying the newest nuget soundingerprinting library.
I am trying to do a duplicate matching, however I cannot find a way to do the 
FindDuplicates from https://github.com/AddictedCS/soundfingerprinting.duplicatesdetector/blob/master/src/SoundFingerprinting.DuplicatesDetector/DuplicatesDetectorService.cs
with the newest Soundfingerprinting library?
What am I missing?

**Comment by AddictedCS** [comment]
I haven't updated the references to the newest SoundFingerprinting library in the demo app. Will do so later. Probably missed the `QueryFingerprintService` reference.

**Comment by AddictedCS** [comment]
`DuplicatesDetectorService` is an internal class used for finding duplicate matches. It uses `QueryFingerprintService` which is internal as well. I didn't make it public since the only way to query the datastore should be done via `QueryCommandBuilder`. 

If you would like to replicate the same mechanism of finding duplicates just create `QueryCommands` and issue requests to the datastore.
